module.exports.descriptors = [
    'Lively', 
    'Vibrant', 
    'Festive', 
    'Electric', 
    'Energetic', 
    'Exciting', 
    'Colorful', 
    'Dynamic', 
    'Thrilling', 
    'Buzzing', 
    'Fun-filled', 
    'Entertaining',  
    'Joyful', 
    'Spirited', 
    'Celebratory', 
    'Exuberant', 
    'High-spirited', 
    'Animated', 
    'Tech',
    'Best Ever',
    'Never Seen',
    'Indias Biggest',
    'Summer',
    'Winter',
    'Spring',
    'Autumn',
    'Halloween',
    'Christmas',
    'New Year',
    'Annnual',
    'Cultural',
    'Entreprenurial',
]

module.exports.venues = [
    'Apex Arena', 
    'Boombox Ballroom', 
    'Cosmic Club', 
    'Summit Stadium', 
    'Amplify Auditorium', 
    'Aurora Amphitheater', 
    'Pulse Pavilion', 
    'Prime Park', 
    'Blissful Beach', 
    'Sonic Square', 
    'Phenomenal Plaza', 
    'Stellar Street', 
    'Grove Garden', 
    'Fury Field', 
    'Retro Rooftop', 
    'Wild Warehouse', 
    'Lush Lounge', 
    'Blaze Bar', 
    'Mystic Mansion', 
    'Celestial Cruise Ship'
]

module.exports.names = [
    'Event', 
    'Gathering', 
    'Celebration', 
    'Festivity', 
    'Occasion', 
    'Get-Together', 
    'Meet-Up', 
    'Happening', 
    'Party', 
    'Concert', 
    'Festival', 
    'Expo', 
    'Fair', 
    'Conference', 
    'Symposium', 
    'Seminar', 
    'Workshop', 
    'Retreat', 
    'Convention', 
    'Exhibition',
    'Fest',
    'Concet',
    'Party',
    'Carnival',
    'Fiesta',
    'Rave',
    'Mixer',
    'Jam',
    'Bash',
    'Fete',
    'Block Party',
    'Mardi Gras'
]
